#! /usr/bin/env zsh

DOT_DIR="$HOME/niri-config"

bindkey -e
zstyle :compinstall filename "$HOME/.zshrc"

setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt EXTENDED_GLOB
setopt AUTO_MENU
setopt AUTO_LIST
setopt prompt_subst

autoload bashcompinit && bashcompinit

autoload -Uz compinit
compinit

source "$DOT_DIR/scripts/shellrc"
