font_family JetBrainsMono Nerd Font
font_size 12
linux_display_server wayland
scrollback_lines 10000
confirm_os_window_close 0
window_padding_width 6
background_opacity  0.97
background_blur 1
tab_bar_style fade
tab_fade 1
active_tab_font_style   bold
inactive_tab_font_style bold
shell fish

include dank-theme.conf
include dank-tabs.conf
include local.conf
