#! /usr/bin/env bash

DOT_DIR="$HOME/.local/share/linux-config"

export VOLTA_HOME="$HOME/.volta"
export PATH="$HOME/.local/share/flatpak/exports/bin:$DOT_DIR/bin:$HOME/.pixi/bin:$HOME/bin:$HOME/.local/bin:$VOLTA_HOME/bin:$PATH"

export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS"

has_cmd() {
    command -v "$1" >/dev/null 2>&1
}

is_zsh() {
    [ -n "$ZSH_VERSION" ]
}

is_bash() {
    [ -n "$BASH_VERSION" ]
}

if has_cmd micro; then
    export EDITOR="micro"
elif has_cmd nvim; then
    export EDITOR="nvim"
elif has_cmd vim; then
    export EDITOR="vim"
elif has_cmd vi; then
    export EDITOR="vi"
elif has_cmd nano; then
    export EDITOR="nano"
fi

if has_cmd code; then
    VISUAL="code --wait"
elif has_cmd zed; then
    VISUAL="zed --wait"
elif flatpak list | grep -qi "com.visualstudio.code"; then
    # shellcheck disable=SC2034
    VISUAL="flatpak run com.visualstudio.code --wait"
fi

case $- in
*i*) ;;
*) return ;;
esac

if [ -d "$HOME/.local/share/pnpm" ]; then
    export PNPM_HOME="/$HOME/.local/share/pnpm"
    case ":$PATH:" in
    *":$PNPM_HOME:"*) ;;
    *) export PATH="$PNPM_HOME:$PATH" ;;
    esac
fi

if has_cmd starship; then
    is_zsh && eval "$(starship init zsh)"
    is_bash && eval "$(starship init bash)"
fi

if has_cmd fzf; then
    is_bash && eval "$(fzf --bash)"
    is_zsh && eval "$(fzf --zsh)"
fi

if has_cmd zoxide; then
    is_bash && eval "$(zoxide init bash)"
    is_zsh && eval "$(zoxide init zsh)"
fi

if has_cmd carapace; then
    # shellcheck disable=SC1090
    source <(carapace _carapace)
fi

if ! has_cmd bat && has_cmd batcat; then
    alias b='batcat'
    alias cat='batcat'
fi

alias ls="eza --icons --group-directories-first"
has_cmd fd-find && alias fd='fd-find'
has_cmd fdfind && alias fd="fdfind"

if has_cmd uv; then
    uv-jupyter-standalone() {
        uv tool run jupyter lab
    }

    uv-marimo-standalone() {
        uvx --with pyzmq --from "marimo[sandbox]" marimo edit --sandbox
    }
fi

if has_cmd mise; then
    is_bash && eval "$(~/.local/bin/mise activate bash --shims)"
    is_zsh && eval "$(~/.local/bin/mise activate zsh --shims)"
fi

if ! has_cmd rustc; then
    # shellcheck disable=SC1091
    [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
fi

if has_cmd /home/linuxbrew/.linuxbrew/bin/brew; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

alias c='code'
alias g='git'
alias h='btm'
alias i='pikman install'
alias u="pikman update && pikman upgrade"
alias p='pikman'
alias pi="pixi global install"
alias t='tmux'
alias v='nvim'
alias s='rg'
alias f='fd-find'
alias kitty-theme='kitty +kitten themes'

alias gs='git stash -u'
alias gp='git push'
alias gb='git branch'
alias gbc='git checkout -b'
alias gsl='git stash list'
alias gst='git status'
alias gsu='git status -u'
alias gcan='git commit --amend --no-edit'
alias gsa='git stash apply'
alias gfm='git pull'
alias gcm='git commit --message'
alias gia='git add'
alias gco='git checkout'
alias dms-logs='journalctl --user -u dms -f'

alias stls='sudo systemctl status'
alias stle='sudo systemctl enable --now'
alias stld='sudo systemctl disable'
alias stlp='sudo systemctl stop'
alias stlr='sudo systemctl restart'
alias stlg='sudo systemctl list-units'
alias stlf='sudo systemctl list-units --all --state=failed'

alias utle='systemctl --user enable --now'
alias utld='systemctl --user disable'
alias utlp='systemctl --user stop'
alias utlr='systemctl --user restart'
alias utlg='systemctl --user list-units'
alias utlf='systemctl --user list-units --all --state=failed'

# shellcheck disable=SC1090
[ -f ~/.localshellrc ] && source ~/.localshellrc
