#! /usr/bin/env bash

export VOLTA_HOME="$HOME/.volta"
export PATH="$HOME/.opencode/bin:$PATH:$HOME/bin:$HOME/.local/bin:$VOLTA_HOME/bin:$PATH"

export XDG_DATA_DIRS="/home/pervez/.local/share/flatpak/exports/share:$XDG_DATA_DIRS"

export EDITOR="code --wait"
export VISUAL="code --wait"
# export EDITOR="zed --wait"
# export EDITOR="nvim"

has_cmd() {
    command -v "$1" >/dev/null 2>&1
}

is_zsh() {
    [ -n "$ZSH_VERSION" ]
}

is_bash() {
    [ -n "$BASH_VERSION" ]
}

case $- in
*i*) ;;
*) return ;;
esac

is_zsh && eval "$(starship init zsh)"
is_bash && eval "$(starship init bash)"

is_bash && eval "$(fzf --bash)"
is_zsh && eval "$(fzf --zsh)"

is_bash && eval "$(zoxide init bash)"
is_zsh && eval "$(zoxide init zsh)"

alias c='code'
alias g='git'
alias h='btm'
alias i='pikman install'
alias u="pikman update && pikman upgrade"
alias p='pikman'
alias t='tmux'
alias v='nvim'
alias s='rg'
alias f='fd-find'
alias kitty-theme='kitty +kitten themes'

alias ce='chezmoi edit'
alias ca='chezmoi apply'
alias cs='chezmoi status'
alias cu='chezmoi update'
alias cw='$HOME/.local/share/chezmoi/scripts/chezmoi-sync & disown'
alias cA='chezmoi add'
alias cf='chezmoi forget'
alias ccd='chezmoi cd'
alias ced="EDITOR='code --wait' chezmoi edit"

if ! has_cmd bat && has_cmd batcat; then
    alias b='batcat'
    alias cat='batcat'
fi

alias ls="eza --icons --group-directories-first"
alias fd='fd-find'

jupyter-lab() {
    cd ~/jupyter-lab || {
        echo "Error: Directory ~/jupyter-lab does not exist."
        return
    }
    .venv/bin/jupyter lab
}

if has_cmd mise; then
    is_bash && eval "$(~/.local/bin/mise activate bash)"
    is_zsh && eval "$(~/.local/bin/mise activate zsh)"
fi

if ! has_cmd rustc; then
    # shellcheck disable=SC1091
    [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
fi

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

system_update() {
    pikman update && pikman upgrade
    pikman --flatpak update --user -y
    pikman --flatpak update -y

    has_cmd mise && mise self-update
    has_cmd mise && mise upgrade --bump
    chezmoi update
}

alias stls='sudo systemctl status'
alias stle='sudo systemctl enable --now'
alias stld='sudo systemctl disable'
alias stlp='sudo systemctl stop'
alias stlr='sudo systemctl restart'
alias stlg='sudo systemctl list-units'
alias stlf='sudo systemctl list-units --all --state=failed'

alias utle='systemctl --user enable --now'
alias utld='systemctl --user disable'
alias utlp='systemctl --user stop'
alias utlr='systemctl --user restart'
alias utlg='systemctl --user list-units'
alias utlf='systemctl --user list-units --all --state=failed'
